### ISSUE TITLE
Accept header not recognized

### ISSUE THREAD

**Issue by devabir93** [bambuser/bambuser-exampleplayer-android#3]
Please can you help me, I cannot display any broadcast and i got this error :
Accept header not recognized
the header i am using is "application/vnd.bambuser.v1+json" and try to use multiple headers but there is no response.

**Comment by rasapetter** [comment]
Hi there, sorry for the late reply!

That header looks right to me. Where did you configure the headers? Did you follow the instructions in README?

**Comment by devabir93** [comment]
thank u, i did it, just didn't use the function get latest uri, and all done.
